title: Fonasa.info
baseurl: "" 
url: "https://fonasa.info"
collections:
  pages:
    output: true
permalink: /:categories/:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
kramdown:
parse_block_html: true
markdown: kramdown
collections:
  posts:
    permalink: /blog/:title/
include:
  - blog/feed.xml
